### 
// Get all quotes.
GET http://localhost:5080/api/quotes
Accept: application/json

###
// Get quote by id.

GET http://localhost:5080/api/quotes/1
Accept: application/json

###
// Get quotes based on tag.
GET http://localhost:5080/api/quotes/tag/2
Accept: application/json

###
// Get all tags.
GET http://localhost:5080/api/quotes/tags
Accept: application/json

###
// Get a random quote.
GET http://localhost:5080/api/quotes/random
Accept: application/json

###
// Add a quote.
POST http://localhost:5080/api/quotes
Content-Type: application/json

{
    "Content": "This is a quote by me.",
    "Author": "Sebastian"
}

###
// Update a quote.
PATCH http://localhost:5080/api/quotes/8
Content-Type: application/json

{
  "Content": "This is an updated quote by someone else.",
  "Author": "bruh"
}

###
// Add a tag.
POST http://localhost:5080/api/quotes/tag
Content-Type: application/json

{
  "tagName": "Inspirational"
}

###
// Add a tag to a quote.
POST http://localhost:5080/api/quotes/16/tag/1

###
// Increase the like count.
POST http://localhost:5080/api/quotes/1/like

###
//Reset like count.
PUT http://localhost:5080/api/quotes/1/like

###
// Delete quote.
DELETE http://localhost:5080/api/quotes/14

###
//Delete tag.
DELETE http://localhost:5080/api/quotes/tag/6

###